### ISSUE TITLE
nie działa

### ISSUE THREAD

**Issue by Nircek** [Nircek/circuiter#7]
During deleting element
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\mzepp\OneDrive\programming\python\circuiter\main.py", line 332, in onkey
    e.onkey(ev)
  File "C:\Users\mzepp\OneDrive\programming\python\circuiter\main.py", line 76, in onkey
    self.parent.rm(self.UUID)
TypeError: 'pos' object is not callable

**Comment by Nircek** [comment]
Solved in efcd738.
