### ISSUE TITLE
Portable Tkinter things

### ISSUE THREAD

**Issue by Nircek** [Nircek/circuiter#8]
You have to change portability for both Windows and Linux, so there's output in Ubuntu for delete, shift, backslach and function keys:
```
<KeyPress event keysym=Delete keycode=119 char='\x7f' x=1122 y=380>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "./main.py", line 351, in onkey
    b = gates[ev.keycode-111]
IndexError: list index out of range
<KeyPress event keysym=Shift_L keycode=50 x=1128 y=165>
<KeyPress event state=Shift keysym=Delete keycode=119 char='\x7f' x=1128 y=165>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "./main.py", line 351, in onkey
    b = gates[ev.keycode-111]
IndexError: list index out of range
<KeyPress event keysym=backslash keycode=51 char='\\' x=1128 y=165>
<KeyPress event keysym=Shift_L keycode=50 x=1128 y=165>
<KeyPress event state=Shift keysym=bar keycode=51 char='|' x=1128 y=165>
<KeyPress event keysym=slash keycode=61 char='/' x=1128 y=165>
<KeyPress event keysym=Shift_L keycode=50 x=1128 y=165>
<KeyPress event state=Shift keysym=question keycode=61 char='?' x=1128 y=165>
<KeyPress event keysym=F1 keycode=67 x=1128 y=165>
<KeyPress event keysym=F2 keycode=68 x=1128 y=165>
<KeyPress event keysym=F3 keycode=69 x=1128 y=165>
<KeyPress event keysym=F4 keycode=70 x=1128 y=165>
<KeyPress event keysym=F5 keycode=71 x=1128 y=165>
<KeyPress event keysym=F6 keycode=72 x=1128 y=165>
```

**Comment by Nircek** [comment]
Solved in 800e65f. Wait for pull request.
